# Generated by Django 3.0.2 on 2020-01-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortalTreningowy', '0002_auto_20200122_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='level',
            new_name='plans',
        ),
    ]
