# Generated by Django 3.0.2 on 2020-01-25 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortalTreningowy', '0003_auto_20200123_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSessionNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_notes', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_weight', models.FloatField()),
                ('user_vo2max', models.FloatField()),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PortalTreningowy.TrainingSession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PortalTreningowy.User')),
            ],
        ),
    ]
