# Generated by Django 3.0.2 on 2020-01-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalTreningowy', '0005_auto_20200126_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsessionnotes',
            name='hr_max',
            field=models.IntegerField(default=190),
            preserve_default=False,
        ),
    ]
